# Cloud Build configuration for deploying to Cloud Run
steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sweet-shop-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sweet-shop-backend:latest'
      - './backend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/sweet-shop-backend:$COMMIT_SHA'

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sweet-shop-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sweet-shop-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production'

  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sweet-shop-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sweet-shop-frontend:latest'
      - './frontend'

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/sweet-shop-frontend:$COMMIT_SHA'

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sweet-shop-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sweet-shop-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/sweet-shop-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/sweet-shop-backend:latest'
  - 'gcr.io/$PROJECT_ID/sweet-shop-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/sweet-shop-frontend:latest'
